import type { Metadata } from "next";
import "./globals.css";
import MainProvider from "@/provider/main/main.provider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className="h-full bg-gray-100">
            <body className="h-full">
                <MainProvider>{children}</MainProvider>
            </body>
        </html>
    );
}
